/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mydemo_1_myapplication_NativeUtils */

#ifndef _Included_mydemo_1_myapplication_NativeUtils
#define _Included_mydemo_1_myapplication_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mydemo_1_myapplication_NativeUtils
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mydemo_11_myapplication_NativeUtils_getStr__
  (JNIEnv *, jclass);

/*
 * Class:     mydemo_1_myapplication_NativeUtils
 * Method:    getStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mydemo_11_myapplication_NativeUtils_getStr__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
